name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Nuget restore
      run: nuget restore

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Run unit tests
      run: |
        $vsDevPath = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise"
        Import-Module "${vsDevPath}\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
        Enter-VsDevShell -VsInstallPath "${vsDevPath}" -DevCmdArguments '-arch=x64'
        msbuild SshAgentLibTests
        ./scripts/coverage.ps1

    - uses: codecov/codecov-action@v2
      with:
        directory: ./coverage
